import { Injectable } from '@nestjs/common';
import fs from 'node:fs';
import path from 'node:path';
import type { AgentSpec, WorkflowSpec } from '@agent-builder/shared-contracts';
import type { CodeGenerationEngine, GenerationContext, GenerationResult } from './engine';

/**
 * MockEngine — a degenerate engine that writes a minimal placeholder project
 * (README + main stub). Used to run the end-to-end UI flow when neither a real
 * model nor OpenCode is available and the full TemplateEngine isn't desired.
 * Distinct from TemplateEngine (which produces the full spec-driven tree).
 */
@Injectable()
export class MockEngine implements CodeGenerationEngine {
  readonly name = 'mock' as const;

  async generate(
    spec: AgentSpec | WorkflowSpec,
    context: GenerationContext,
    callbacks?: { onFile?: (file: { path: string; size: number }) => void },
  ): Promise<GenerationResult> {
    fs.mkdirSync(context.projectPath, { recursive: true });
    const files: { path: string; size: number }[] = [];

    const readme = `# ${spec.name} (mock)\n\nGenerated by MockEngine — placeholder project for UI demonstration.\n`;
    const readmePath = 'README.md';
    fs.writeFileSync(path.join(context.projectPath, readmePath), readme, 'utf8');
    files.push({ path: readmePath, size: readme.length });
    callbacks?.onFile?.(files[0]);

    const main = `print("${spec.name} (mock)")\n`;
    const mainPath = 'src/main.py';
    fs.mkdirSync(path.join(context.projectPath, 'src'), { recursive: true });
    fs.writeFileSync(path.join(context.projectPath, mainPath), main, 'utf8');
    files.push({ path: mainPath, size: main.length });
    callbacks?.onFile?.(files[1]);

    return { engine: 'mock', projectPath: context.projectPath, files, warnings: [], mock: true };
  }
}
